name: Tag - Minor  (vX.X+1.0)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Tag
        run: |
          ./src/bin/build-scripts/tag.minor.sh
