name: Tag - Minor

on: workflow_dispatch

jobs:
  tag-minor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Tag
        run: |
          ./src/bin/build-scripts/tag.minor.sh
